export const GAME_REFERENCES = [
  // PLATFORMERS
  { k: ["mario", "super mario"], g: "platformer", c: "fantasy_royal", m: "run jump collect coins reach flag", s: "hero_journey", p: "both", b: "side-scroll tiles gravity Goomba enemies powerups" },
  { k: ["zelda", "link"], g: "adventure", c: "forest_earth", m: "explore dungeon solve puzzles defeat boss", s: "discovery", p: "both", b: "top-down rooms keys doors heart containers" },
  { k: ["sonic", "speed platformer"], g: "platformer", c: "neon_arcade", m: "run fast loops spin attack", s: "hero_journey", p: "both", b: "momentum physics rings speed terrain" },
  { k: ["mega man", "megaman"], g: "platformer", c: "neon_arcade", m: "defeat bosses steal their weapon", s: "hero_journey", p: "both", b: "boss select weapon weakness jump shoot" },
  { k: ["celeste", "precision platformer"], g: "platformer", c: "neon_arcade", m: "dash climb mountain precision jumps", s: "hero_journey", p: "both", b: "tight physics dash cooldown spike death retry" },
  { k: ["hollow knight", "metroidvania"], g: "metroidvania", c: "horror_bleak", m: "explore interconnected map gain abilities", s: "discovery", p: "both", b: "side-scroll map rooms ability gates" },
  { k: ["ori", "metroidvania emotional"], g: "metroidvania", c: "forest_earth", m: "fluid platforming restore forest", s: "hero_journey", p: "both", b: "dash bash launch emotional beats" },
  { k: ["shovel knight", "retro platformer"], g: "platformer", c: "retro_cabinet", m: "shovel bounce defeat knights", s: "hero_journey", p: "both", b: "shovel drop bounce checkpoints" },
  { k: ["crash bandicoot", "3d platformer"], g: "platformer", c: "tropical_vibrant", m: "forward run spin jump crates", s: "hero_journey", p: "both", b: "lane runner spin jump wumpa crates" },
  { k: ["spyro", "dragon platformer"], g: "platformer", c: "fantasy_royal", m: "glide flame charge collect gems", s: "discovery", p: "both", b: "3D-ish glide flame charge gems" },
  { k: ["banjo", "collectathon"], g: "platformer", c: "forest_earth", m: "collect jiggies unlock worlds", s: "discovery", p: "both", b: "hub world collectibles ability unlock" },
  { k: ["castlevania", "vania"], g: "platformer", c: "horror_bleak", m: "whip platform through castle", s: "revenge", p: "both", b: "whip subweapons stairs knockback" },
  { k: ["limbo", "atmospheric"], g: "platformer", c: "monochrome_noir", m: "silhouette boy traverse dangers", s: "escape", p: "both", b: "silhouette physics puzzles dark mood" },
  { k: ["inside", "puzzle platformer"], g: "platformer", c: "monochrome_noir", m: "escape facility solve environmental puzzles", s: "escape", p: "both", b: "silhouette chase puzzles mood" },
  { k: ["fez", "dimension puzzle"], g: "platformer", c: "retro_cabinet", m: "rotate world 2D/3D perspective", s: "discovery", p: "both", b: "rotate view hidden paths collect" },
  { k: ["braid", "time puzzle"], g: "puzzle", c: "fantasy_royal", m: "rewind time solve platform puzzles", s: "time_loop", p: "both", b: "rewind mechanic keys doors" },
  { k: ["subway surfers", "endless runner"], g: "platformer", c: "neon_arcade", m: "dodge obstacles collect coins endless", s: "escape", p: "mobile", b: "3-lane swipe jump roll speed up" },
  { k: ["temple run"], g: "platformer", c: "tropical_vibrant", m: "auto-run turn jump slide collect", s: "escape", p: "mobile", b: "lane turn swipe obstacles tilt" },
  { k: ["kirby"], g: "platformer", c: "pastel_cute", m: "inhale enemies copy abilities float", s: "hero_journey", p: "both", b: "copy power float inhale spit" },
  { k: ["donkey kong", "dk"], g: "platformer", c: "tropical_vibrant", m: "barrel roll jump collect bananas", s: "rescue", p: "both", b: "side-scroll barrels throw vehicles" },
  { k: ["rayman"], g: "platformer", c: "candy_bright", m: "limbless hero punch jump swing", s: "hero_journey", p: "both", b: "hair helicopter punch sliding" },
  { k: ["metroid"], g: "metroidvania", c: "space_cosmic", m: "explore alien planet collect power-ups", s: "survival", p: "both", b: "side-scroll power gates missile beam" },
  { k: ["yoshi"], g: "platformer", c: "candy_bright", m: "eat enemies make eggs throw", s: "rescue", p: "both", b: "tongue eat egg throw platform" },
  { k: ["wario ware", "microgame"], g: "party", c: "candy_bright", m: "rapid random micro-challenges", s: "survival", p: "both", b: "3-second random games speed up" },

  // SHOOTERS & ACTION
  { k: ["minecraft"], g: "3d_sandbox", c: "forest_earth", m: "place break blocks build structures", s: "sandbox_free", p: "both", b: "WebGL voxel cubes first-person place/remove" },
  { k: ["fortnite", "battle royale"], g: "shooter", c: "candy_bright", m: "last player standing shrinking zone", s: "last_stand", p: "both", b: "top-down zone shrink loot pickups elimination" },
  { k: ["call of duty", "cod", "fps"], g: "3d_fps", c: "military_olive", m: "shoot enemies complete mission", s: "revenge", p: "desktop", b: "raycast corridors gunfire reload HUD" },
  { k: ["doom"], g: "3d_fps", c: "lava_volcanic", m: "blast demons through maze levels", s: "revenge", p: "desktop", b: "raycast fast movement shotgun splash damage" },
  { k: ["quake", "boomer shooter"], g: "3d_fps", c: "lava_volcanic", m: "arena deathmatch rocket jump strafe", s: "last_stand", p: "desktop", b: "raycast rocket launcher bunny hop fast pace" },
  { k: ["half life", "half-life"], g: "3d_fps", c: "military_olive", m: "crowbar physics scripted events", s: "escape", p: "desktop", b: "raycast gravity gun scripted events" },
  { k: ["halo"], g: "3d_fps", c: "space_cosmic", m: "spartan shoot aliens ring world", s: "hero_journey", p: "both", b: "raycast dual wield shield recharge vehicles" },
  { k: ["bioshock"], g: "3d_fps", c: "ocean_deep", m: "plasmids combat underwater city explore", s: "corruption", p: "desktop", b: "raycast elemental powers morality choices" },
  { k: ["dishonored", "stealth action"], g: "stealth", c: "steampunk_brass", m: "blink teleport possess eliminate", s: "revenge", p: "both", b: "blink ability non-lethal lethal chaos rating" },
  { k: ["space invaders"], g: "shooter", c: "space_cosmic", m: "shoot descending alien waves", s: "last_stand", p: "both", b: "player ship bottom bullet pool shield blocks" },
  { k: ["galaga", "shmup"], g: "shooter", c: "space_cosmic", m: "dodge and shoot enemy formations", s: "hero_journey", p: "both", b: "vertical scroll enemy patterns capture rescue" },
  { k: ["asteroids"], g: "shooter", c: "space_cosmic", m: "rotate thrust shoot asteroids split", s: "survival", p: "both", b: "wrap screen thrust rotate split rocks" },
  { k: ["missile command"], g: "shooter", c: "retro_cabinet", m: "intercept missiles protect cities", s: "last_stand", p: "both", b: "click intercept trails cities" },
  { k: ["cuphead", "boss rush"], g: "shooter", c: "retro_cabinet", m: "pattern memorize boss bullet hell", s: "underdog", p: "both", b: "boss phases bullet patterns parry" },
  { k: ["contra", "run and gun"], g: "shooter", c: "military_olive", m: "side scroll shoot forward base", s: "hero_journey", p: "both", b: "run gun spread weapon platforms" },
  { k: ["metal slug", "arcade run gun"], g: "shooter", c: "military_olive", m: "side scroll vehicles heavy weapons", s: "hero_journey", p: "both", b: "side scroll vehicle swap grenades" },
  { k: ["duck hunt", "light gun"], g: "shooter", c: "forest_earth", m: "shoot ducks before they fly away", s: "survival", p: "both", b: "click shoot moving targets dog" },
  { k: ["overwatch", "hero shooter"], g: "shooter", c: "candy_bright", m: "team objectives unique hero abilities", s: "hero_journey", p: "both", b: "heroes abilities payload control point" },
  { k: ["apex legends", "battle royale hero"], g: "shooter", c: "neon_arcade", m: "squad BR abilities ping system", s: "last_stand", p: "both", b: "zone shrink legend ability revive" },
  { k: ["pubg"], g: "shooter", c: "military_olive", m: "100 players last squad wins", s: "survival", p: "both", b: "zone loot circle top-down or 2D" },
  { k: ["counter-strike", "cs", "csgo"], g: "3d_fps", c: "military_olive", m: "bomb plant defuse round economy", s: "heist", p: "desktop", b: "rounds buy phase sites raycast or top-down" },
  { k: ["valorant", "tactical shooter"], g: "shooter", c: "neon_arcade", m: "abilities plus precise gunplay rounds", s: "hero_journey", p: "desktop", b: "agent abilities spike plant sites" },
  { k: ["defender", "side shooter"], g: "shooter", c: "space_cosmic", m: "side scroll rescue humans shoot", s: "hero_journey", p: "both", b: "side scroll humans pickup scanner" },
  { k: ["vampire survivors", "bullet heaven"], g: "action", c: "horror_bleak", m: "auto-attack survive horde timer", s: "survival", p: "both", b: "auto weapons XP level up horde" },
  { k: ["destiny", "looter shooter"], g: "shooter", c: "space_cosmic", m: "shoot loot gear missions", s: "hero_journey", p: "both", b: "loot rarity missions abilities" },
  { k: ["borderlands", "looter fps"], g: "shooter", c: "western_dust", m: "shoot loot comic guns co-op feel", s: "discovery", p: "both", b: "gungen loot comic outlines" },
  { k: ["warframe", "action looter"], g: "action", c: "space_cosmic", m: "fast parkour melee ranged grind", s: "hero_journey", p: "both", b: "parkour slide melee abilities" },
  { k: ["tank trouble", "tank"], g: "action", c: "military_olive", m: "bounce shots hit opponent tank", s: "last_stand", p: "both", b: "tank rotate fire ricochet maze" },
  { k: ["geometry wars", "twin stick"], g: "shooter", c: "neon_arcade", m: "twin stick shoot geometric enemies", s: "survival", p: "both", b: "twin stick all-direction shoot geometric shapes" },

  // ARCADE
  { k: ["tetris"], g: "puzzle", c: "retro_cabinet", m: "rotate falling blocks clear lines", s: "tower_climb", p: "both", b: "grid collision line clear speed up" },
  { k: ["pac-man", "pacman"], g: "arcade", c: "neon_arcade", m: "eat dots avoid ghosts power pellets", s: "escape", p: "both", b: "maze grid ghost AI chase scatter modes" },
  { k: ["snake"], g: "arcade", c: "neon_arcade", m: "grow longer eating food avoid walls", s: "underdog", p: "both", b: "grid segments direction queue speed up" },
  { k: ["pong"], g: "arcade", c: "retro_cabinet", m: "paddle ball rally score points", s: "last_stand", p: "both", b: "ball physics paddle AI or 2P" },
  { k: ["flappy bird", "flappy"], g: "arcade", c: "candy_bright", m: "tap fly through pipe gaps", s: "survival", p: "mobile", b: "gravity tap impulse pipe collision score" },
  { k: ["katamari", "roll ball"], g: "arcade", c: "candy_bright", m: "roll ball collect objects grow", s: "sandbox_free", p: "both", b: "ball grows sticky physics timer" },
  { k: ["doodle jump", "vertical jump"], g: "arcade", c: "minimal_clean", m: "bounce upward avoid falling", s: "tower_climb", p: "mobile", b: "auto bounce platforms moving enemies" },
  { k: ["crossy road", "crossy"], g: "arcade", c: "retro_cabinet", m: "cross roads rivers rails timing", s: "survival", p: "mobile", b: "lane hop timing vehicles logs" },
  { k: ["agar.io", "agar"], g: "arcade", c: "candy_bright", m: "eat smaller blobs grow avoid bigger", s: "underdog", p: "both", b: "circle eat split mass leaderboard" },
  { k: ["slither.io", "slither"], g: "arcade", c: "neon_arcade", m: "snake multiplayer grow trap others", s: "survival", p: "both", b: "snake boost trap orbit kill" },
  { k: ["fruit ninja"], g: "arcade", c: "tropical_vibrant", m: "slice flying fruit avoid bombs", s: "survival", p: "mobile", b: "swipe slice trajectories combo" },
  { k: ["pinball"], g: "arcade", c: "neon_arcade", m: "flipper ball score bumpers", s: "tower_climb", p: "both", b: "physics ball flippers bumpers multiball" },
  { k: ["helix jump", "helix"], g: "arcade", c: "neon_arcade", m: "ball falls through helix gaps", s: "tower_climb", p: "mobile", b: "rotate helix smash platforms fall" },
  { k: ["stack", "stack tower"], g: "arcade", c: "minimal_clean", m: "time block drops stack perfectly", s: "tower_climb", p: "mobile", b: "moving block tap stack trim miss" },
  { k: ["brick breaker", "breakout", "arkanoid"], g: "arcade", c: "neon_arcade", m: "bounce ball break all bricks", s: "tower_climb", p: "both", b: "paddle ball bricks powerups" },
  { k: ["frogger"], g: "arcade", c: "forest_earth", m: "cross road dodge cars hop logs", s: "survival", p: "both", b: "grid hop dodge logs cars lives" },
  { k: ["centipede"], g: "shooter", c: "forest_earth", m: "shoot descending centipede mushrooms", s: "last_stand", p: "both", b: "shooter downward mushrooms flea spider" },
  { k: ["space war", "spacewar"], g: "arcade", c: "space_cosmic", m: "two ships orbit star shoot", s: "last_stand", p: "both", b: "gravity orbit thrust shoot torpedo" },
  { k: ["piano tiles", "tap tiles"], g: "rhythm", c: "minimal_clean", m: "tap black tiles avoid white", s: "tower_climb", p: "mobile", b: "scroll tiles tap speed up miss end" },

  // PUZZLE
  { k: ["portal"], g: "puzzle", c: "minimal_clean", m: "solve spatial puzzles with portals", s: "escape", p: "desktop", b: "chamber buttons doors portal teleport" },
  { k: ["angry birds"], g: "puzzle", c: "candy_bright", m: "launch projectiles destroy structures", s: "revenge", p: "mobile", b: "slingshot aim physics blocks pigs" },
  { k: ["candy crush", "match 3", "match-3"], g: "puzzle", c: "candy_bright", m: "swap tiles match three clear board", s: "tower_climb", p: "mobile", b: "grid swap cascade special candies moves limit" },
  { k: ["2048"], g: "puzzle", c: "zen_meditation", m: "slide tiles merge to 2048", s: "tower_climb", p: "both", b: "grid slide merge spawn 2/4" },
  { k: ["minesweeper"], g: "puzzle", c: "minimal_clean", m: "reveal cells avoid mines deduce", s: "mystery", p: "both", b: "grid click flag numbers reveal" },
  { k: ["sokoban", "push boxes"], g: "puzzle", c: "zen_meditation", m: "push crates onto targets", s: "escape", p: "both", b: "grid push undo level targets" },
  { k: ["bejeweled"], g: "puzzle", c: "fantasy_royal", m: "swap gems match three cascade", s: "tower_climb", p: "both", b: "grid swap timer special gems" },
  { k: ["cut the rope", "physics puzzle"], g: "puzzle", c: "candy_bright", m: "cut ropes feed candy to monster", s: "hero_journey", p: "mobile", b: "physics rope cut gravity stars" },
  { k: ["monument valley", "optical puzzle"], g: "puzzle", c: "pastel_cute", m: "navigate impossible architecture", s: "discovery", p: "mobile", b: "iso optical illusions rotate paths" },
  { k: ["sudoku"], g: "puzzle", c: "zen_meditation", m: "fill grid 1-9 no repeats", s: "mystery", p: "both", b: "9x9 grid validation hints mistakes" },
  { k: ["crossword"], g: "word", c: "minimal_clean", m: "fill intersecting word clues", s: "mystery", p: "both", b: "grid clues across down validation" },
  { k: ["hangman"], g: "word", c: "retro_cabinet", m: "guess letters before figure complete", s: "survival", p: "both", b: "word blanks keyboard wrong limit" },
  { k: ["tetris 99", "battle puzzle"], g: "puzzle", c: "neon_arcade", m: "tetris attack other boards", s: "last_stand", p: "both", b: "line clear send garbage attack" },
  { k: ["witness", "line puzzle"], g: "puzzle", c: "zen_meditation", m: "draw lines solve panel rules", s: "mystery", p: "desktop", b: "panels rules symbols line draw" },
  { k: ["baba is you"], g: "puzzle", c: "minimal_clean", m: "push words to change rules", s: "mystery", p: "both", b: "word blocks rules push break logic" },
  { k: ["the room", "escape puzzle"], g: "puzzle", c: "steampunk_brass", m: "examine objects find hidden mechanisms", s: "mystery", p: "mobile", b: "tap inspect zoom solve mechanisms" },
  { k: ["opus magnum", "alchemy puzzle"], g: "puzzle", c: "steampunk_brass", m: "program alchemical machine transmute", s: "mystery", p: "desktop", b: "arms program loop transmute elements" },
  { k: ["stephen sausage roll"], g: "puzzle", c: "minimal_clean", m: "roll sausage on grill without burning", s: "mystery", p: "both", b: "grid fork roll precise unforgiving" },
  { k: ["obra dinn", "deduction"], g: "puzzle", c: "monochrome_noir", m: "deduce cause of death from scenes", s: "mystery", p: "desktop", b: "flashback scene deduce match fate" },
  { k: ["little alchemy", "combine"], g: "puzzle", c: "zen_meditation", m: "combine elements discover recipes", s: "discovery", p: "both", b: "drag combine element list discovery" },

  // RPG
  { k: ["pokemon", "pokémon"], g: "rpg", c: "pastel_cute", m: "catch creatures turn-based battle", s: "discovery", p: "both", b: "encounter rate HP types rock-paper-scissors" },
  { k: ["final fantasy", "jrpg"], g: "rpg", c: "fantasy_royal", m: "party combat story choices level up", s: "hero_journey", p: "both", b: "turn menu attack magic item flee XP" },
  { k: ["dark souls", "souls"], g: "action", c: "horror_bleak", m: "precise combat dodge punishing enemies", s: "corruption", p: "desktop", b: "stamina bar dodge roll telegraphed attacks" },
  { k: ["elden ring", "open world rpg"], g: "adventure", c: "fantasy_royal", m: "explore vast world defeat bosses", s: "hero_journey", p: "desktop", b: "mini open map landmarks boss gate" },
  { k: ["undertale"], g: "rpg", c: "retro_cabinet", m: "choose fight mercy or negotiate", s: "romance_choice", p: "both", b: "bullet hell dodge dialogue mercy option" },
  { k: ["disco elysium", "rpg narrative"], g: "rpg", c: "cyberpunk", m: "skill checks dialogue solve murder", s: "mystery", p: "desktop", b: "skill checks thought cabinet dialogue" },
  { k: ["wow", "world of warcraft", "mmo"], g: "rpg", c: "fantasy_royal", m: "quest grind gear raid boss", s: "hero_journey", p: "desktop", b: "quest log gear slots dungeon boss" },
  { k: ["runescape", "mmorpg"], g: "rpg", c: "fantasy_royal", m: "skill grind trade explore", s: "discovery", p: "both", b: "skill levels inventory grind quests" },
  { k: ["diablo", "action rpg", "hack slash"], g: "isometric", c: "lava_volcanic", m: "click kill loot upgrade gear", s: "corruption", p: "both", b: "iso click move loot drops skills" },
  { k: ["path of exile", "arpg"], g: "isometric", c: "horror_bleak", m: "skill tree loot maps endgame", s: "corruption", p: "desktop", b: "skill web loot filters maps" },
  { k: ["chrono trigger"], g: "rpg", c: "fantasy_royal", m: "time travel party combat story", s: "hero_journey", p: "both", b: "ATB combo techs time era travel" },
  { k: ["secret of mana"], g: "rpg", c: "forest_earth", m: "action combat ring menu spells", s: "hero_journey", p: "both", b: "action hit ring menu stamina weapon levels" },
  { k: ["dragon quest"], g: "rpg", c: "fantasy_royal", m: "turn RPG classic hero fights slime", s: "hero_journey", p: "both", b: "encounter turn command menu classic" },
  { k: ["fire emblem", "tactics rpg"], g: "isometric", c: "fantasy_royal", m: "grid battles permadeath units", s: "hero_journey", p: "both", b: "iso grid class triangle support range" },
  { k: ["xcom", "tactical"], g: "strategy", c: "military_olive", m: "squad turn combat cover aliens", s: "last_stand", p: "desktop", b: "grid cover overwatch action points" },
  { k: ["bloodborne", "gothic action"], g: "action", c: "horror_bleak", m: "aggressive combat rally HP", s: "corruption", p: "desktop", b: "aggressive dodge rally risk reward" },
  { k: ["sekiro", "parry action"], g: "action", c: "zen_meditation", m: "deflect attacks posture kill", s: "hero_journey", p: "both", b: "posture bar deflect timing deathblow" },
  { k: ["devil may cry", "stylish action"], g: "action", c: "lava_volcanic", m: "combo rank stylish combat", s: "revenge", p: "both", b: "combo rank style meter varied attacks" },
  { k: ["bayonetta", "spectacle fighter"], g: "fighting", c: "fantasy_royal", m: "dodge witch time combo enemies", s: "revenge", p: "both", b: "dodge witch time combo weapons" },
  { k: ["monster hunter", "boss hunt"], g: "action", c: "forest_earth", m: "track hunt large monster craft gear", s: "hero_journey", p: "both", b: "boss patterns parts carve gear" },
  { k: ["genshin impact", "gacha rpg"], g: "rpg", c: "fantasy_royal", m: "open world collect characters elements", s: "hero_journey", p: "both", b: "element reactions wish characters open world" },
  { k: ["stardew valley", "farming"], g: "simulation", c: "forest_earth", m: "farm crops befriend villagers seasons", s: "discovery", p: "both", b: "grid plant water harvest day cycle shop" },

  // RACING
  { k: ["need for speed", "racing game"], g: "racing", c: "neon_arcade", m: "race opponents drift boost win", s: "underdog", p: "both", b: "pseudo-3D road or top-down lap checkpoints" },
  { k: ["mario kart"], g: "racing", c: "candy_bright", m: "kart race with items and shortcuts", s: "hero_journey", p: "both", b: "top-down items banana shell boost" },
  { k: ["hill climb racing"], g: "racing", c: "candy_bright", m: "physics drive hills fuel management", s: "survival", p: "mobile", b: "2D physics gas brake rotate" },
  { k: ["trackmania", "time trial race"], g: "racing", c: "neon_arcade", m: "race track beat ghost time", s: "tower_climb", p: "both", b: "time trial checkpoints ghost replay" },
  { k: ["forza", "sim racing"], g: "racing", c: "minimal_clean", m: "realistic drive tuning circuits", s: "underdog", p: "desktop", b: "circuit racing lines braking apex" },
  { k: ["gran turismo", "gt"], g: "racing", c: "minimal_clean", m: "license tests car collection", s: "tower_climb", p: "both", b: "license tests car unlock garage" },
  { k: ["road rash", "bike brawl"], g: "racing", c: "sunset_warm", m: "race bikes punch opponents", s: "underdog", p: "both", b: "side scroll race punch weapon cops" },
  { k: ["burnout", "crash racing"], g: "racing", c: "sunset_warm", m: "crash boost race traffic takedown", s: "last_stand", p: "both", b: "boost crashdown traffic drift" },
  { k: ["f-zero", "future racing"], g: "racing", c: "neon_arcade", m: "hover car racing speed extreme", s: "tower_climb", p: "both", b: "pseudo-3D hover energy shield death pit" },
  { k: ["rocket league"], g: "sports", c: "neon_arcade", m: "cars hit ball into goal aerial", s: "underdog", p: "both", b: "physics ball boost jump aerial" },
  { k: ["neon bike", "bike"], g: "racing", c: "neon_arcade", m: "balance bike perform tricks", s: "underdog", p: "both", b: "physics balance pedal jump trick" },

  // STRATEGY
  { k: ["chess"], g: "strategy", c: "minimal_clean", m: "checkmate opponent king", s: "mystery", p: "both", b: "8x8 board piece rules check highlight" },
  { k: ["civilization", "civ", "4x"], g: "strategy", c: "forest_earth", m: "build empire research conquer", s: "discovery", p: "desktop", b: "hex or grid cities resources turns" },
  { k: ["age of empires", "rts"], g: "strategy", c: "military_olive", m: "gather resources build army destroy base", s: "hero_journey", p: "desktop", b: "select units move attack build queue" },
  { k: ["starcraft"], g: "strategy", c: "space_cosmic", m: "micro units macro economy race", s: "last_stand", p: "desktop", b: "minerals gas units build order micro" },
  { k: ["warcraft", "rts"], g: "strategy", c: "fantasy_royal", m: "orcs vs humans resource war", s: "hero_journey", p: "desktop", b: "top-down resource mine build fight" },
  { k: ["worms", "artillery"], g: "strategy", c: "tropical_vibrant", m: "aim projectile destroy enemy worms", s: "last_stand", p: "both", b: "turn aim power wind destructible terrain" },
  { k: ["clash of clans"], g: "strategy", c: "sunset_warm", m: "build base raid enemies", s: "underdog", p: "mobile", b: "grid buildings troops deploy raid" },
  { k: ["league of legends", "lol", "moba"], g: "moba", c: "fantasy_royal", m: "push lanes destroy enemy nexus", s: "hero_journey", p: "desktop", b: "3 lanes minions abilities cooldowns" },
  { k: ["dota"], g: "moba", c: "forest_earth", m: "team strategy destroy ancient", s: "last_stand", p: "desktop", b: "lanes heroes items teamfight" },
  { k: ["plants vs zombies", "pvz"], g: "tower_defense", c: "forest_earth", m: "place plants stop zombie waves", s: "last_stand", p: "both", b: "lanes sun economy plant types waves" },
  { k: ["bloons", "bloons td"], g: "tower_defense", c: "candy_bright", m: "pop balloon paths with monkey towers", s: "tower_climb", p: "both", b: "path curves tower upgrade pop layers" },
  { k: ["kingdom rush", "tower defense"], g: "tower_defense", c: "fantasy_royal", m: "place towers path defend kingdom", s: "last_stand", p: "both", b: "path tower types upgrade special" },
  { k: ["gta", "grand theft auto"], g: "action", c: "cyberpunk", m: "drive explore complete missions", s: "heist", p: "both", b: "top-down city cars pedestrians missions" },
  { k: ["among us"], g: "party", c: "space_cosmic", m: "complete tasks find impostor", s: "mystery", p: "both", b: "tasks bar emergency vote impostor kill" },
  { k: ["hades", "roguelike action"], g: "roguelike", c: "lava_volcanic", m: "escape underworld repeated deaths upgrade", s: "escape", p: "both", b: "rooms boons death meta-upgrade dialogue" },

  // SIMULATION
  { k: ["simcity", "city builder"], g: "simulation", c: "minimal_clean", m: "zone build manage city resources", s: "sandbox_free", p: "desktop", b: "grid zoning happiness budget disasters" },
  { k: ["the sims", "life sim"], g: "simulation", c: "pastel_cute", m: "manage needs relationships career", s: "sandbox_free", p: "both", b: "needs bars actions furniture mood" },
  { k: ["rollercoaster tycoon", "theme park"], g: "simulation", c: "candy_bright", m: "build rides manage park profit", s: "underdog", p: "desktop", b: "place rides paths happiness ticket income" },
  { k: ["animal crossing"], g: "simulation", c: "pastel_cute", m: "decorate island befriend animals", s: "sandbox_free", p: "both", b: "grid place furniture villagers chat" },
  { k: ["harvest moon", "story of seasons"], g: "simulation", c: "sunset_warm", m: "farm life romance festivals", s: "romance_choice", p: "both", b: "crops hearts calendar gifts" },
  { k: ["kerbal space", "rocket"], g: "simulation", c: "space_cosmic", m: "build rocket reach orbit", s: "discovery", p: "both", b: "parts assemble launch physics orbit" },
  { k: ["cities skylines"], g: "simulation", c: "forest_earth", m: "plan city traffic economy growth", s: "sandbox_free", p: "desktop", b: "road layout zones budget traffic" },
  { k: ["factorio", "automation"], g: "simulation", c: "military_olive", m: "automate factory build rocket", s: "sandbox_free", p: "desktop", b: "belt splitter inserter factory chain" },
  { k: ["planet zoo", "zoo sim"], g: "simulation", c: "tropical_vibrant", m: "build zoo manage animal habitats", s: "sandbox_free", p: "desktop", b: "path habitat animals needs rating" },
  { k: ["spore", "evolution"], g: "simulation", c: "tropical_vibrant", m: "evolve creature through stages", s: "discovery", p: "both", b: "creature editor eat grow evolve" },
  { k: ["tamagotchi", "pet"], g: "simulation", c: "pastel_cute", m: "feed clean play keep pet happy", s: "hero_journey", p: "mobile", b: "needs meters actions evolution" },
  { k: ["farming simulator"], g: "simulation", c: "forest_earth", m: "operate tractors harvest sell crops", s: "sandbox_free", p: "both", b: "vehicle steering field harvest market" },
  { k: ["euro truck", "trucking"], g: "simulation", c: "sunset_warm", m: "drive cargo routes park deliver", s: "escape", p: "both", b: "road driving speed limit delivery" },
  { k: ["flight simulator", "plane"], g: "simulation", c: "ocean_deep", m: "pilot aircraft land navigate", s: "discovery", p: "desktop", b: "instruments throttle pitch landing" },
  { k: ["no man's sky", "exploration space"], g: "adventure", c: "space_cosmic", m: "explore planets gather resources", s: "discovery", p: "both", b: "planet surface gather scan ship" },
  { k: ["slime rancher"], g: "simulation", c: "candy_bright", m: "corral slimes harvest plorts sell", s: "discovery", p: "both", b: "vacuum shoot slimes corrals farm" },
  { k: ["powerwash simulator"], g: "simulation", c: "minimal_clean", m: "clean surfaces with pressure washer", s: "sandbox_free", p: "both", b: "spray dirt progress bar satisfaction" },

  // HORROR
  { k: ["resident evil", "survival horror"], g: "horror", c: "horror_bleak", m: "limited ammo escape monsters puzzles", s: "escape", p: "both", b: "dark rooms inventory keys jump scares" },
  { k: ["silent hill", "psychological horror"], g: "horror", c: "monochrome_noir", m: "explore foggy town uncover trauma", s: "mystery", p: "desktop", b: "fog overlay radio static puzzles" },
  { k: ["five nights", "fnaf"], g: "horror", c: "horror_bleak", m: "survive nights watch cameras close doors", s: "survival", p: "both", b: "camera switch power limit animatronics" },
  { k: ["outlast", "stealth horror"], g: "horror", c: "horror_bleak", m: "hide from enemies record evidence", s: "escape", p: "desktop", b: "hide spots stamina chase camera night" },
  { k: ["amnesia", "dark descent"], g: "horror", c: "horror_bleak", m: "hide from monster manage sanity", s: "escape", p: "desktop", b: "sanity meter darkness hide no fight" },
  { k: ["cry of fear"], g: "horror", c: "monochrome_noir", m: "disturbing walking horror gun scarce", s: "corruption", p: "desktop", b: "flashlight fear scarce ammo disturbing" },
  { k: ["little nightmares"], g: "platformer", c: "horror_bleak", m: "hide from giant creatures escape vessel", s: "escape", p: "both", b: "side-scroll hide sneak giant scale" },
  { k: ["backrooms", "liminal horror"], g: "horror", c: "horror_bleak", m: "escape endless liminal space entities", s: "survival", p: "both", b: "wandering rooms yellow walls entities" },

  // ROGUELIKES
  { k: ["slay the spire", "deckbuilder roguelike"], g: "roguelike", c: "horror_bleak", m: "build deck fight encounters climb spire", s: "tower_climb", p: "both", b: "card rewards energy paths relics" },
  { k: ["binding of isaac", "roguelike"], g: "roguelike", c: "horror_bleak", m: "random rooms items permadeath runs", s: "corruption", p: "both", b: "room clear item pickup floor boss" },
  { k: ["enter the gungeon", "bullet hell roguelike"], g: "roguelike", c: "retro_cabinet", m: "dodge bullet patterns dungeon floors", s: "escape", p: "both", b: "dodge roll blanks items floors" },
  { k: ["nuclear throne", "top-down roguelike"], g: "roguelike", c: "military_olive", m: "mutants fight to throne", s: "last_stand", p: "both", b: "top-down horde mutations" },
  { k: ["risk of rain", "platform roguelike"], g: "roguelike", c: "military_olive", m: "stack items difficulty scales time", s: "survival", p: "both", b: "items stack difficulty timer teleporter" },
  { k: ["dead cells", "roguevania"], g: "metroidvania", c: "cyberpunk", m: "fast combat procedural castle", s: "escape", p: "both", b: "fast combat biomes permanent unlocks" },
  { k: ["balatro", "poker roguelike"], g: "roguelike", c: "neon_arcade", m: "poker hands score beat blinds", s: "underdog", p: "both", b: "poker hands jokers multipliers blinds" },
  { k: ["noita", "physics roguelike"], g: "roguelike", c: "lava_volcanic", m: "craft wand spells pixel physics cave", s: "corruption", p: "desktop", b: "pixel physics wand spell craft dungeon" },
  { k: ["spelunky"], g: "roguelike", c: "sunset_warm", m: "dig explore random cave permadeath", s: "discovery", p: "both", b: "cave dig bomb rope permadeath trap" },

  // CARD GAMES
  { k: ["solitaire", "klondike"], g: "card", c: "forest_earth", m: "stack cards ace to king four suits", s: "escape", p: "both", b: "card piles drag rules auto-move" },
  { k: ["poker", "texas holdem"], g: "card", c: "western_dust", m: "bet best hand bluff opponents", s: "heist", p: "both", b: "hand rank bet fold call AI tells" },
  { k: ["blackjack", "21"], g: "card", c: "fantasy_royal", m: "reach 21 without busting", s: "survival", p: "both", b: "hit stand dealer rules chip bet" },
  { k: ["hearthstone", "ccg"], g: "card", c: "fantasy_royal", m: "play minion spell cards reduce HP", s: "hero_journey", p: "both", b: "mana curve hand board minion attack" },
  { k: ["gwent"], g: "card", c: "military_olive", m: "rows strategy beat opponent two rounds", s: "strategy", p: "both", b: "rows power pass bluff leader ability" },
  { k: ["legends of runeterra"], g: "card", c: "fantasy_royal", m: "attack defend nexus champion cards", s: "hero_journey", p: "both", b: "attack token champion level burst" },

  // SPORTS
  { k: ["fifa", "soccer game"], g: "sports", c: "forest_earth", m: "score goals control team", s: "last_stand", p: "both", b: "top-down ball pass shoot timer" },
  { k: ["nba", "basketball"], g: "sports", c: "sunset_warm", m: "shoot hoops beat shot clock", s: "underdog", p: "both", b: "arc shot timing defender block" },
  { k: ["golf", "mini golf"], g: "sports", c: "zen_meditation", m: "aim power putt into hole", s: "tower_climb", p: "both", b: "drag aim power obstacles par" },
  { k: ["bowling"], g: "sports", c: "retro_cabinet", m: "roll ball knock pins timing", s: "tower_climb", p: "both", b: "power angle spin pin physics" },
  { k: ["boxing", "punch out"], g: "fighting", c: "retro_cabinet", m: "dodge patterns punch openings", s: "underdog", p: "both", b: "tell patterns dodge punch stamina" },
  { k: ["rollerblade", "skate", "skating"], g: "sports", c: "neon_arcade", m: "trick combos score lines", s: "underdog", p: "both", b: "halfpipe tricks timing score multiplier" },
  { k: ["tony hawk", "skateboard"], g: "sports", c: "cyberpunk", m: "combo tricks reach score goal", s: "underdog", p: "both", b: "2D park grind jump trick chain" },
  { k: ["wii sports", "motion sport"], g: "sports", c: "candy_bright", m: "motion swing throw punch bowl", s: "underdog", p: "both", b: "mouse drag timing power sport mode" },

  // FIGHTING GAMES
  { k: ["street fighter", "fighting game"], g: "fighting", c: "neon_arcade", m: "combo attacks deplete opponent health", s: "revenge", p: "both", b: "two fighters health special meter inputs" },
  { k: ["mortal kombat"], g: "fighting", c: "lava_volcanic", m: "brutal combos finish opponent", s: "revenge", p: "both", b: "fighters blood fatality button combo" },
  { k: ["smash bros", "super smash", "platform fighter"], g: "fighting", c: "candy_bright", m: "knock opponents off platform stock", s: "last_stand", p: "both", b: "% damage knockback platform stock" },
  { k: ["tekken"], g: "fighting", c: "military_olive", m: "3d fighter combo juggle punish", s: "revenge", p: "both", b: "3D sidestep juggle combo move list" },
  { k: ["soul calibur", "weapon fighter"], g: "fighting", c: "fantasy_royal", m: "weapon combat ring out 8-way run", s: "revenge", p: "both", b: "weapon 8-way ring out guard impact" },
  { k: ["king of fighters", "kof"], g: "fighting", c: "neon_arcade", m: "3-on-3 team fighter cancel chains", s: "revenge", p: "both", b: "team order cancel max mode chain" },

  // RHYTHM
  { k: ["guitar hero", "rhythm"], g: "rhythm", c: "neon_arcade", m: "hit notes in time to music", s: "tower_climb", p: "both", b: "falling lanes timing windows combo" },
  { k: ["dance dance revolution", "ddr"], g: "rhythm", c: "neon_arcade", m: "step arrows on beat", s: "tower_climb", p: "both", b: "4 lanes arrows scroll BPM score" },
  { k: ["osu", "rhythm tap"], g: "rhythm", c: "pastel_cute", m: "click circles sliders on beat", s: "tower_climb", p: "desktop", b: "approach circles timing accuracy combo" },
  { k: ["geometry dash"], g: "rhythm", c: "neon_arcade", m: "one-button jump through deadly obstacles", s: "tower_climb", p: "both", b: "auto-scroll tap jump sync spikes" },
  { k: ["beat saber", "vr rhythm"], g: "rhythm", c: "neon_arcade", m: "slice blocks with sabers on beat", s: "tower_climb", p: "both", b: "mouse slice block direction beat" },
  { k: ["crypt of necrodancer", "rhythm roguelike"], g: "rhythm", c: "horror_bleak", m: "move on beat dungeon enemies", s: "tower_climb", p: "both", b: "beat step dungeon enemy rhythm" },

  // WORD GAMES
  { k: ["wordle"], g: "word", c: "minimal_clean", m: "guess five letter word six tries", s: "mystery", p: "both", b: "letter grid keyboard color feedback" },
  { k: ["scrabble", "word tiles"], g: "word", c: "zen_meditation", m: "place letters form words score", s: "tower_climb", p: "both", b: "letter rack board place score bonus" },
  { k: ["wheel of fortune", "word game show"], g: "word", c: "neon_arcade", m: "spin solve phrase puzzle", s: "mystery", p: "both", b: "phrase grid spin letters buy vowel" },

  // PARTY & SOCIAL
  { k: ["fall guys"], g: "party", c: "candy_bright", m: "race obstacle courses last bean standing", s: "survival", p: "both", b: "physics obstacles elimination rounds" },
  { k: ["mario party", "board party"], g: "party", c: "candy_bright", m: "dice board minigames compete", s: "hero_journey", p: "both", b: "board path dice minigame rounds" },
  { k: ["jackbox", "trivia party"], g: "party", c: "neon_arcade", m: "answer prompts vote funniest", s: "mystery", p: "both", b: "prompt input vote reveal scores" },
  { k: ["trivia", "quiz"], g: "party", c: "minimal_clean", m: "answer questions score highest", s: "tower_climb", p: "both", b: "question timer 4 choices streak" },
  { k: ["jeopardy", "trivia quiz"], g: "party", c: "minimal_clean", m: "pick category answer question", s: "tower_climb", p: "both", b: "category grid buzz answer wager" },
  { k: ["cooking", "cooking mama", "overcooked"], g: "party", c: "candy_bright", m: "prepare orders under time pressure", s: "survival", p: "both", b: "recipe steps timer multi-task chaos" },
  { k: ["club penguin", "social"], g: "party", c: "ice_frost", m: "mini-games socialize decorate igloo", s: "sandbox_free", p: "both", b: "rooms minigames chat emotes" },

  // IDLE & CASUAL
  { k: ["cookie clicker"], g: "idle", c: "pastel_cute", m: "click bake cookies buy upgrades", s: "underdog", p: "both", b: "big clicker upgrade list passive CPS prestige" },
  { k: ["adventure capitalist", "idle tycoon"], g: "idle", c: "minimal_clean", m: "buy businesses multiply profits", s: "underdog", p: "both", b: "businesses managers angels prestige" },
  { k: ["idle miner", "mining idle"], g: "idle", c: "military_olive", m: "hire miners dig deeper upgrade", s: "underdog", p: "both", b: "shaft levels workers upgrade depth" },
  { k: ["realm grinder", "idle kingdom"], g: "idle", c: "fantasy_royal", m: "faction choice idle conquest", s: "corruption", p: "both", b: "factions spells idle coins spells" },
  { k: ["universal paperclips", "idle clicker"], g: "idle", c: "minimal_clean", m: "make paperclips automate universe", s: "corruption", p: "both", b: "automate stages absurd escalation" },
  { k: ["kittens game", "text idle"], g: "idle", c: "zen_meditation", m: "manage cat civilization resources", s: "discovery", p: "both", b: "resource text buttons tech tree" },
  { k: ["slot machine", "slots"], g: "casual", c: "fantasy_royal", m: "spin reels match symbols win", s: "underdog", p: "both", b: "reels spin paylines credits animation" },
  { k: ["roulette"], g: "casual", c: "fantasy_royal", m: "bet on number/color spin wheel", s: "survival", p: "both", b: "wheel spin bet table payout" },
  { k: ["fishing", "fishing game"], g: "casual", c: "ocean_deep", m: "cast reel catch fish sell", s: "discovery", p: "both", b: "cast timing reel tension fish types" },
  { k: ["dress up", "fashion"], g: "casual", c: "pastel_cute", m: "style character score outfit", s: "sandbox_free", p: "mobile", b: "wardrobe drag items score theme" },

  // ADVENTURE & NARRATIVE
  { k: ["visual novel", "dating sim"], g: "visual_novel", c: "pastel_cute", m: "read story make dialogue choices", s: "romance_choice", p: "both", b: "text box portraits choices branches" },
  { k: ["danganronpa", "murder mystery vn"], g: "visual_novel", c: "neon_arcade", m: "investigate trials debate truth", s: "mystery", p: "both", b: "investigate clues trial minigame" },
  { k: ["phoenix wright", "ace attorney"], g: "visual_novel", c: "minimal_clean", m: "cross-examine find contradictions", s: "mystery", p: "both", b: "evidence press present objection" },
  { k: ["monkey island", "point click"], g: "adventure", c: "tropical_vibrant", m: "inventory puzzles dialogue pirate comedy", s: "hero_journey", p: "both", b: "point click inventory use combine talk" },
  { k: ["journey"], g: "adventure", c: "ice_frost", m: "travel desert to mountain wordless", s: "discovery", p: "both", b: "glide sand cloth symbols no text" },
  { k: ["what remains of edith finch", "walking sim"], g: "adventure", c: "sunset_warm", m: "explore house discover family stories", s: "mystery", p: "both", b: "walk interact trigger story cutscene" },
  { k: ["firewatch"], g: "adventure", c: "sunset_warm", m: "hike radio talk investigate mystery", s: "mystery", p: "both", b: "walk radio dialogue choice mystery" },
  { k: ["night in the woods", "narrative"], g: "adventure", c: "sunset_warm", m: "explore town talk friends mystery", s: "mystery", p: "both", b: "platformer walk talk dialogue explore" },

  // SANDBOX
  { k: ["terraria", "2d sandbox"], g: "sandbox", c: "fantasy_royal", m: "mine craft fight bosses explore", s: "discovery", p: "both", b: "side-scroll dig place craft boss" },
  { k: ["starbound", "space sandbox"], g: "sandbox", c: "space_cosmic", m: "explore planets build base", s: "discovery", p: "both", b: "planet hop mine build NPC" },
  { k: ["roblox", "user world"], g: "sandbox", c: "candy_bright", m: "mini-game hub obstacle variety", s: "sandbox_free", p: "both", b: "obstacle course lobby multiple modes" },

  // STEALTH
  { k: ["metal gear", "stealth"], g: "stealth", c: "military_olive", m: "sneak past guards avoid detection", s: "heist", p: "both", b: "vision cones hide boxes alert levels" },
  { k: ["hitman", "assassin"], g: "stealth", c: "minimal_clean", m: "eliminate target creatively undetected", s: "heist", p: "both", b: "disguise zones target patrol silent kill" },
  { k: ["thief", "shadow stealth"], g: "stealth", c: "monochrome_noir", m: "steal in shadows avoid light", s: "heist", p: "desktop", b: "light meter shadow move rope arrow" },

  // BOARD GAMES
  { k: ["catan", "settlers"], g: "board", c: "sunset_warm", m: "settle island trade resources build", s: "sandbox_free", p: "both", b: "hex grid resource trade build card" },
  { k: ["monopoly"], g: "board", c: "candy_bright", m: "buy property build houses bankrupt", s: "underdog", p: "both", b: "board dice property buy build trade" },
  { k: ["risk", "world domination"], g: "board", c: "military_olive", m: "conquer territories roll dice armies", s: "last_stand", p: "both", b: "territory dice attack defend card" },
  { k: ["checkers", "draughts"], g: "board", c: "minimal_clean", m: "capture all opponent pieces king", s: "strategy", p: "both", b: "diagonal jump king crown win" },
  { k: ["reversi", "othello"], g: "board", c: "minimal_clean", m: "flip discs control most pieces", s: "strategy", p: "both", b: "flip between corner edge strategy" },
  { k: ["go", "weiqi"], g: "board", c: "zen_meditation", m: "surround territory capture stones", s: "strategy", p: "both", b: "grid place stone territory capture" },

  // PROGRAMMING & LOGIC GAMES
  { k: ["hacknet", "hacking"], g: "puzzle", c: "monochrome_noir", m: "type commands hack terminals", s: "mystery", p: "desktop", b: "terminal commands ls ssh nmap hack" },
  { k: ["shenzhen io", "programming"], g: "puzzle", c: "cyberpunk", m: "program microcontrollers assembly code", s: "mystery", p: "desktop", b: "assembly language chips test loop" },
  { k: ["zachlike", "engineering puzzle"], g: "puzzle", c: "minimal_clean", m: "pipe assemble machine pass tests", s: "mystery", p: "both", b: "assembly optimize cost cycles test" },

  // AUTO BATTLERS
  { k: ["teamfight tactics", "tft", "auto battler", "auto chess"], g: "strategy", c: "fantasy_royal", m: "place units auto fight synergies", s: "tower_climb", p: "both", b: "bench board synergy items econ rounds" },
  { k: ["underlords", "dota auto chess"], g: "strategy", c: "fantasy_royal", m: "draft heroes auto battle rounds", s: "tower_climb", p: "both", b: "draft alliances shop level interest" },

  // RETRO & CLASSIC
  { k: ["donkey kong arcade"], g: "platformer", c: "retro_cabinet", m: "climb girders avoid barrels", s: "rescue", p: "both", b: "climbing ladders barrels hammer levels" },
  { k: ["q-bert", "qbert"], g: "arcade", c: "retro_cabinet", m: "hop cubes change colors avoid", s: "tower_climb", p: "both", b: "iso cubes hop color change enemies" },
  { k: ["dig dug"], g: "arcade", c: "retro_cabinet", m: "pump inflate enemies dig tunnels", s: "survival", p: "both", b: "dig tunnel pump inflate rock drop" },
  { k: ["bomberman"], g: "arcade", c: "retro_cabinet", m: "place bombs destroy walls trap enemies", s: "last_stand", p: "both", b: "grid bomb blast radius powerup multiplayer" },
  { k: ["burgertime"], g: "arcade", c: "candy_bright", m: "drop burger parts on enemies", s: "escape", p: "both", b: "ladder platform burger drop pepper" },
  { k: ["moon patrol"], g: "shooter", c: "space_cosmic", m: "drive moon buggy shoot jump craters", s: "survival", p: "both", b: "side scroll shoot up ahead crater jump" },
  { k: ["scramble", "side scroller shoot"], g: "shooter", c: "space_cosmic", m: "fly ship shoot bases fuel collect", s: "survival", p: "both", b: "side scroll fuel drop bomb shoot" },
  { k: ["joust"], g: "arcade", c: "retro_cabinet", m: "flap lance enemy knights on birds", s: "last_stand", p: "both", b: "flap platform joust enemy level eggs" },
  { k: ["1942", "wwii shooter"], g: "shooter", c: "military_olive", m: "vertical scroll plane shoot avoid", s: "survival", p: "both", b: "vertical scroll plane bomb loop" },

  // MOBILE
  { k: ["clash royale", "real time card"], g: "strategy", c: "fantasy_royal", m: "deploy cards towers real time", s: "last_stand", p: "mobile", b: "card elixir deploy lane towers" },
  { k: ["brawl stars"], g: "shooter", c: "candy_bright", m: "top-down brawlers team mode", s: "last_stand", p: "mobile", b: "top-down move shoot brawler gems" },
  { k: ["hay day", "mobile farm"], g: "simulation", c: "sunset_warm", m: "farm grow sell trade neighbors", s: "sandbox_free", p: "mobile", b: "plant grow sell truck trade boat" },
  { k: ["candy crush saga"], g: "puzzle", c: "candy_bright", m: "match 3 candy saga levels", s: "tower_climb", p: "mobile", b: "swap cascade special level goal" },
  { k: ["cut the rope remastered"], g: "puzzle", c: "pastel_cute", m: "cut ropes stars collect candy", s: "hero_journey", p: "mobile", b: "rope cut gravity star collect" },

  // MISC UNIQUE
  { k: ["katana zero", "action neo noir"], g: "action", c: "cyberpunk", m: "plan replay one-hit kill platformer", s: "mystery", p: "both", b: "slow time plan one-hit cassette" },
  { k: ["hotline miami", "top down action"], g: "action", c: "neon_arcade", m: "top-down fast brutal plan execute", s: "corruption", p: "both", b: "top-down one-hit plan masks brutal" },
  { k: ["superhot", "time shooter"], g: "shooter", c: "minimal_clean", m: "time moves when you move shoot", s: "mystery", p: "both", b: "time-stop bullet plan matrix" },
  { k: ["untitled goose game", "goose"], g: "sandbox", c: "minimal_clean", m: "cause chaos as goose honk items", s: "sandbox_free", p: "both", b: "stealth carry drop honk task list" },
  { k: ["goat simulator"], g: "sandbox", c: "candy_bright", m: "be goat cause physics chaos lick", s: "sandbox_free", p: "both", b: "ragdoll physics lick attach jetpack" },
  { k: ["surgeon simulator"], g: "casual", c: "minimal_clean", m: "awkward physics surgery controls", s: "sandbox_free", p: "both", b: "awkward controls physics organ drop" },
  { k: ["papers please", "bureaucracy"], g: "puzzle", c: "monochrome_noir", m: "inspect documents approve deny border", s: "corruption", p: "desktop", b: "doc check rules violations quota" },
  { k: ["typewriter", "type game", "typing"], g: "casual", c: "minimal_clean", m: "type words before enemies reach", s: "survival", p: "both", b: "word appear type delete speed" },

  // VR
  { k: ["vr", "virtual reality"], g: "3d_world", c: "neon_arcade", m: "immersive 360 look interact", s: "discovery", p: "both", b: "mouse look WASD interact reticle" },
  { k: ["ar", "augmented reality"], g: "casual", c: "candy_bright", m: "overlay game on camera view", s: "discovery", p: "mobile", b: "camera-like overlay tap place objects" },
];
