export const GENRES = [
  "action", "adventure", "arcade", "board", "card", "casual", "educational",
  "fighting", "horror", "idle", "metroidvania", "moba", "party", "platformer",
  "puzzle", "racing", "rhythm", "roguelike", "rpg", "sandbox", "shooter",
  "simulation", "sports", "stealth", "strategy", "survival", "tower_defense",
  "visual_novel", "word", "3d_fps", "3d_racing", "3d_sandbox", "isometric",
];

export const COLOR_PALETTES = {
  neon_arcade: { bg: "#0a0a0a", accents: ["#ff006e", "#3a86ff", "#06d6a0", "#ffbe0b"], mood: "electric nightlife" },
  sunset_warm: { bg: "#2d1b00", accents: ["#ff6b35", "#f7c59f", "#efefd0", "#004e89"], mood: "cozy adventure" },
  forest_earth: { bg: "#1a3a2a", accents: ["#588157", "#a3b18a", "#dad7cd", "#3a5a40"], mood: "organic calm" },
  ocean_deep: { bg: "#0d2137", accents: ["#1d3557", "#457b9d", "#a8dadc", "#e63946"], mood: "underwater mystery" },
  space_cosmic: { bg: "#020818", accents: ["#7209b7", "#ffd60a", "#4cc9f0", "#f72585"], mood: "weightless wonder" },
  horror_bleak: { bg: "#0d0d0d", accents: ["#8b0000", "#2d5016", "#e8e8d0", "#4a4a4a"], mood: "dread tension" },
  retro_cabinet: { bg: "#1a1a2e", accents: ["#ff0000", "#ffff00", "#00ffff", "#ffffff"], mood: "80s arcade" },
  pastel_cute: { bg: "#fff0f6", accents: ["#ffafcc", "#bde0fe", "#cdb4db", "#ffc8dd"], mood: "kawaii cheerful" },
  fantasy_royal: { bg: "#1a0a2e", accents: ["#ffd700", "#7b2d8b", "#00a86b", "#dc143c"], mood: "epic quest" },
  minimal_clean: { bg: "#f5f5f5", accents: ["#111111", "#e63946"], mood: "brutalist focus" },
  cyberpunk: { bg: "#0d0221", accents: ["#ff0a54", "#00f5d4", "#fee440", "#7b2cbf"], mood: "dystopian tech" },
  western_dust: { bg: "#3d2b1f", accents: ["#c9a66b", "#8b4513", "#f4e4bc", "#5c4033"], mood: "frontier grit" },
  candy_bright: { bg: "#fff5f5", accents: ["#ff6b9d", "#c44569", "#ffa502", "#7bed9f"], mood: "mobile casual" },
  military_olive: { bg: "#1c1f14", accents: ["#4b5320", "#8b8c3e", "#c4a35a", "#d4d4c8"], mood: "tactical combat" },
  steampunk_brass: { bg: "#2a1f1a", accents: ["#b87333", "#cd7f32", "#8b7355", "#daa520"], mood: "industrial vintage" },
  ice_frost: { bg: "#0a1628", accents: ["#a8d8ea", "#aa96da", "#fcbad3", "#ffffd2"], mood: "frozen ethereal" },
  lava_volcanic: { bg: "#1a0500", accents: ["#ff4500", "#ff6347", "#ffd700", "#8b0000"], mood: "intense danger" },
  monochrome_noir: { bg: "#1a1a1a", accents: ["#ffffff", "#888888", "#ff4444"], mood: "film noir" },
  tropical_vibrant: { bg: "#004d40", accents: ["#ff6f00", "#ffca28", "#00e676", "#18ffff"], mood: "island energy" },
  zen_meditation: { bg: "#e8e0d5", accents: ["#6b7f6b", "#a8b5a0", "#d4c5b0", "#8b9d83"], mood: "peaceful focus" },
};

export const STORY_ARCHETYPES = {
  hero_journey: "Ordinary character faces challenge, gains power, defeats threat, returns victorious.",
  escape: "Trapped somewhere — find keys, solve obstacles, reach exit before timer ends.",
  survival: "Resources dwindle, threats escalate, last as long as possible.",
  rescue: "Someone or something must be saved — reach them through hazards.",
  revenge: "Wronged protagonist fights through enemies to confront final boss.",
  discovery: "Explore unknown space, uncover secrets, collect artifacts.",
  tower_climb: "Ascend increasingly difficult floors or waves to prove mastery.",
  last_stand: "Defend a point against endless waves — how long can you hold?",
  heist: "Infiltrate, grab objective, escape without detection.",
  romance_choice: "Dialogue branches affect relationship outcomes — 3 endings minimum.",
  mystery: "Clues scattered in environment — deduce answer to win.",
  underdog: "Weak starter becomes powerful through upgrades and skill.",
  corruption: "Power grows but costs something — risk/reward tension.",
  time_loop: "Fail state resets with retained knowledge or upgrades.",
  sandbox_free: "No forced story — player sets own goals in open creative space.",
};

export const PLATFORM_GUIDES = {
  mobile: "Touch-first: 48px+ buttons, bottom-screen controls, portrait or landscape lock, no hover-only UI, swipe gestures where natural, large readable text 16px+.",
  desktop: "Keyboard + mouse: WASD/arrows primary, click for aim/select, hover tooltips OK, denser HUD acceptable, smaller UI margins.",
  both: "Show on-screen touch buttons AND support keyboard. Scale canvas to viewport. Prevent accidental zoom. Controls panel always visible.",
};

export const MOOD_KEYWORDS = {
  neon_arcade: ["neon", "arcade", "cyber", "synth", "glow", "electric"],
  sunset_warm: ["cozy", "warm", "sunset", "cottage", "autumn", "campfire"],
  forest_earth: ["forest", "nature", "garden", "farm", "jungle", "wood"],
  ocean_deep: ["ocean", "underwater", "sea", "aquatic", "beach", "wave"],
  space_cosmic: ["space", "galaxy", "star", "cosmic", "alien", "planet"],
  horror_bleak: ["horror", "scary", "dark", "haunted", "zombie", "ghost"],
  retro_cabinet: ["retro", "pixel", "8bit", "arcade", "classic", "old school"],
  pastel_cute: ["cute", "kawaii", "pastel", "adorable", "fluffy", "sweet"],
  fantasy_royal: ["fantasy", "magic", "medieval", "dragon", "wizard", "castle"],
  minimal_clean: ["minimal", "clean", "simple", "white", "geometric", "zen"],
  cyberpunk: ["cyberpunk", "dystopia", "hacker", "blade runner", "neon city"],
  western_dust: ["western", "cowboy", "desert", "saloon", "frontier"],
  candy_bright: ["candy", "sweet", "colorful", "mobile", "casual", "pop"],
  military_olive: ["military", "war", "tactical", "soldier", "combat"],
  steampunk_brass: ["steampunk", "brass", "clockwork", "victorian", "gear"],
  ice_frost: ["ice", "snow", "frozen", "winter", "frost", "arctic"],
  lava_volcanic: ["lava", "volcano", "fire", "hell", "inferno", "magma"],
  monochrome_noir: ["noir", "black and white", "detective", "monochrome"],
  tropical_vibrant: ["tropical", "island", "paradise", "palm", "hawaii"],
  zen_meditation: ["zen", "calm", "meditation", "peaceful", "relaxing"],
};
